{ lib, pkgs, isWork, ... }:
# skhd: a hotkey daemon whose only job here is forwarding Option+<letter> to
# OmniWM, which cannot bind more than nine workspaces itself. The letters and
# their apps live in modules/shared/letter-workspaces.nix.
#
# skhd needs the Accessibility permission. The grant is tied to the binary's
# /nix/store path, so it only needs renewing when skhd itself changes, which
# is rare.
let
  letterWorkspaces = import ../shared/letter-workspaces.nix { inherit lib isWork; };

  # Absolute store path: the launchd agent's PATH does not include the
  # home-manager profile where omniwmctl is installed. pkgs.omniwm is the same
  # overlaid derivation home-manager installs (useGlobalPkgs).
  omniwmctl = "${pkgs.omniwm}/bin/omniwmctl";

  binding = ws: ''
    ${ws.skhd.switch} : ${omniwmctl} command switch-workspace ${toString ws.number}
    ${ws.skhd.move} : ${omniwmctl} command move-to-workspace ${toString ws.number}
  '';
in
{
  services.skhd = {
    enable = true;
    skhdConfig = ''
      # Generated by modules/darwin/skhd.nix; edit letter-workspaces.nix instead.
      ${lib.concatMapStrings binding letterWorkspaces}
    '';
  };

  # skhd runs each command with $SHELL. /bin/sh keeps a keypress from starting
  # zsh with its startup files. This has to be the environment: the `.shell`
  # config directive exists only in unreleased skhd, and 0.3.9 rejects the
  # whole file over it, silently leaving no hotkeys bound.
  launchd.user.agents.skhd.serviceConfig.EnvironmentVariables.SHELL = "/bin/sh";
}
